import type { AppRouteMeta, ModuleManifest, PlatformManifest } from "@rinjani/shared-types";

export const platforms: PlatformManifest[] = [
  {
    id: "portal",
    label: "Portal",
    basePath: "/",
    defaultRoute: "/",
    description: "Entry hub for profile, notifications, surveys, search, and admin features.",
    iconKey: "workspace",
    order: 1,
    visibleTo: ["Admin", "User"],
  },
  {
    id: "talent",
    label: "Talent",
    switcherLabel: "Rinjani Talent",
    basePath: "/talent",
    defaultRoute: "/talent",
    description: "Talent journeys, talent management, job tender, and 360 assessment.",
    iconKey: "users",
    order: 2,
    visibleTo: ["Admin", "User"],
  },
  {
    id: "performance",
    label: "Performance",
    switcherLabel: "Rinjani Performance",
    basePath: "/performance",
    defaultRoute: "/performance/my-kpi",
    description: "KPI planning, monitoring, and headquarter dashboards.",
    iconKey: "trophy",
    order: 3,
    visibleTo: ["Admin", "User"],
  },
  {
    id: "performance-v2",
    label: "Performance 2.0",
    switcherLabel: "Performance 2.0 (preview)",
    basePath: "/performance-v2",
    defaultRoute: "/performance-v2/my-kpi",
    description: "Performance 2.0 prototype driven by DIP-1–7 fixtures.",
    iconKey: "trophy",
    order: 4,
    visibleTo: ["Admin", "User"],
  },
];

export const sidebarModules: ModuleManifest[] = [
  { id: "portal-dashboard", label: "Dashboard", routePath: "/", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Default landing page and information hub.", iconKey: "grid", order: 1 },
  { id: "portal-my-profile", label: "My Profile", routePath: "/my-profile", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Employee self-service profile.", iconKey: "users", order: 2 },
  { id: "portal-survey", label: "Survey", routePath: "/survey", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Ongoing and historical employee surveys.", iconKey: "clipboard", order: 3 },
  { id: "portal-policy", label: "HC Digi Policy", routePath: "/hc-policy", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Portal Home", description: "Policy library and support documentation.", iconKey: "file", order: 4 },
  { id: "portal-analytics", label: "Analytics", routePath: "/analytics", parentPlatformId: "portal", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Portal-wide analytics dashboard.", iconKey: "analytics", order: 5 },
  { id: "portal-mail", label: "Mail Management", routePath: "/mail", parentPlatformId: "portal", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Message templates and email administration.", iconKey: "mail", order: 6 },
  { id: "portal-offboarding", label: "Offboarding", routePath: "/offboarding", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Administration", description: "Offboarding process tracking.", iconKey: "briefcase", order: 7 },
  { id: "portal-settings", label: "Settings", routePath: "/settings", parentPlatformId: "portal", visibleTo: ["Admin", "User"], sidebarGroup: "Administration", description: "CMS, user management, notifications, onboarding, and survey administration.", iconKey: "settings", order: 8 },
  { id: "portal-design-system", label: "Design System", routePath: "/design-system", parentPlatformId: "portal", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Admin-only shared component library preview.", iconKey: "grid", order: 9 },
  { id: "portal-enterprise-architecture", label: "Enterprise Architecture", routePath: "/talent/enterprise-architecture", parentPlatformId: "portal", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Architecture cost model and five-year investment projection.", iconKey: "workspace", order: 10 },

  { id: "talent-home", label: "Talent Home", routePath: "/talent", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Talent dashboard and alerts.", iconKey: "grid", order: 1 },
  { id: "talent-supervisor", label: "My Team", routePath: "/talent/supervisor-portal", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Line manager team dashboard and insights.", iconKey: "users", order: 2 },
  { id: "talent-career-aspiration", label: "Career Aspiration", routePath: "/talent/career-aspiration", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Career path and aspiration flow.", iconKey: "target", order: 3 },
  { id: "talent-idp", label: "Development Plan", routePath: "/talent/idp", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Individual development plan routes.", iconKey: "clipboard", order: 4 },
  { id: "talent-360", label: "360 Assessment", routePath: "/talent/360-assessment", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Multi-rater feedback, anonymity, and published reports.", iconKey: "analytics", order: 5 },
  { id: "talent-competency", label: "Competency Assessment", routePath: "/talent/competency-assessment", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Self assessment tools and evaluation reports.", iconKey: "target", order: 6 },
  { id: "talent-job-tender", label: "Job Tender Marketplace", routePath: "/talent/explore", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "My Talent Journey", description: "Explore jobs and application routes.", iconKey: "briefcase", order: 7 },
  { id: "talent-pool", label: "Talent Pool", routePath: "/talent/talent-pool", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Talent pool and profiling.", iconKey: "users", order: 8 },
  { id: "talent-succession", label: "Succession Planning", routePath: "/talent/succession-planning", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Succession dashboards and candidates.", iconKey: "git", order: 9 },
  { id: "talent-classification", label: "Talent Classification", routePath: "/talent/talent-mapping", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "9-box classification and calibration.", iconKey: "grid", order: 10 },
  { id: "talent-review", label: "Talent Review", routePath: "/talent/talent-review", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Talent review pages.", iconKey: "file", order: 11 },
  { id: "talent-committee", label: "Talent Committee Portal", routePath: "/talent/talent-committee", parentPlatformId: "talent", visibleTo: ["Admin", "User"], sidebarGroup: "Talent Management", description: "Talent committee review, sessions, and decisions.", iconKey: "users", order: 12 },
  { id: "talent-job-admin", label: "Job Tender Headquarters", routePath: "/talent/admin/job-tender", parentPlatformId: "talent", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Secondary Assignment (Experience & Learning) and Talent Mobility vacancy administration.", iconKey: "briefcase", order: 13 },
  { id: "talent-idp-admin", label: "IDP Headquarters", routePath: "/talent/admin/idp", parentPlatformId: "talent", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "IDP administration routes.", iconKey: "clipboard", order: 14 },
  { id: "talent-org", label: "Organization Management", routePath: "/talent/org-management", parentPlatformId: "talent", visibleTo: ["Admin"], sidebarGroup: "Administration", description: "Position Master, structure, Band, Job Family, and KSP completeness.", iconKey: "workspace", order: 15 },

  { id: "performance-my-kpi", label: "My KPI", routePath: "/performance/my-kpi", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "Individual KPI dashboard.", iconKey: "trophy", order: 1 },
  { id: "performance-my-team", label: "My Team KPI", routePath: "/performance/my-team-kpi", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "Manager KPI monitoring and planning.", iconKey: "users", order: 2 },
  { id: "performance-library", label: "KPI Library", routePath: "/performance/kpi-library", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "Standard KPI catalog.", iconKey: "clipboard", order: 3 },
  { id: "performance-tree", label: "KPI Tree", routePath: "/performance/kpi-tree", parentPlatformId: "performance", visibleTo: ["Admin", "User"], sidebarGroup: "Performance", description: "KPI alignment visualization.", iconKey: "git", order: 4 },
  { id: "performance-hq", label: "KPI Headquarter", routePath: "/performance/kpi-headquarter", parentPlatformId: "performance", visibleTo: ["Admin"], sidebarGroup: "Performance", description: "Headquarter metrics and configuration.", iconKey: "analytics", order: 5 },

  {
    id: "performance-v2-my-kpi",
    label: "My KPI",
    routePath: "/performance-v2/my-kpi",
    parentPlatformId: "performance-v2",
    visibleTo: ["Admin", "User"],
    sidebarGroup: "Performance",
    description: "Rencana, capaian, refleksi",
    iconKey: "trophy",
    order: 1,
  },
  {
    id: "performance-v2-my-team",
    label: "My Team KPI",
    routePath: "/performance-v2/my-team-kpi",
    defaultChildRoute: "/performance-v2/my-team-kpi/planning",
    parentPlatformId: "performance-v2",
    visibleTo: ["Admin", "User"],
    sidebarGroup: "Performance",
    description: "Tim, persetujuan, verifikasi",
    iconKey: "users",
    order: 2,
  },
  {
    id: "performance-v2-library",
    label: "KPI Library",
    routePath: "/performance-v2/kpi-library",
    parentPlatformId: "performance-v2",
    visibleTo: ["Admin", "User"],
    sidebarGroup: "Performance",
    description: "Kamus definisi standar",
    iconKey: "clipboard",
    order: 3,
  },
  {
    id: "performance-v2-tree",
    label: "KPI Tree",
    routePath: "/performance-v2/kpi-tree",
    parentPlatformId: "performance-v2",
    visibleTo: ["Admin", "User"],
    sidebarGroup: "Performance",
    description: "Alignment seluruh level",
    iconKey: "git",
    order: 4,
  },
  {
    id: "performance-v2-hq",
    label: "KPI HQ",
    routePath: "/performance-v2/kpi-headquarter",
    parentPlatformId: "performance-v2",
    visibleTo: ["Admin"],
    sidebarGroup: "Performance",
    description: "Kebijakan & periode",
    iconKey: "analytics",
    order: 5,
  },
];

export const routeMeta: AppRouteMeta[] = [
  { path: "/", pageTitle: "Portal Dashboard", breadcrumbLabel: "Dashboard", platformId: "portal", moduleId: "portal-dashboard", searchScope: "platform" },
  { path: "/my-profile", pageTitle: "My Profile", breadcrumbLabel: "My Profile", platformId: "portal", moduleId: "portal-my-profile", searchScope: "platform" },
  { path: "/survey", pageTitle: "Survey", breadcrumbLabel: "Survey", platformId: "portal", moduleId: "portal-survey", searchScope: "platform" },
  { path: "/survey/take/:surveyId", pageTitle: "Take Survey", breadcrumbLabel: "Take Survey", platformId: "portal", moduleId: "portal-survey", hidden: true, searchScope: "module" },
  { path: "/survey/analytics/:surveyId", pageTitle: "Survey Analytics", breadcrumbLabel: "Survey Analytics", platformId: "portal", moduleId: "portal-survey", hidden: true, searchScope: "module" },
  { path: "/survey/management", pageTitle: "Survey Management", breadcrumbLabel: "Survey Management", platformId: "portal", moduleId: "portal-settings", hidden: true, searchScope: "module" },
  { path: "/hc-policy", pageTitle: "HC Digi Policy", breadcrumbLabel: "HC Digi Policy", platformId: "portal", moduleId: "portal-policy", searchScope: "global" },
  { path: "/employee-profile/:email", pageTitle: "Employee Profile", breadcrumbLabel: "Employee Profile", platformId: "portal", moduleId: "portal-my-profile", hidden: true, searchScope: "module" },
  { path: "/analytics", pageTitle: "Analytics", breadcrumbLabel: "Analytics", platformId: "portal", moduleId: "portal-analytics", searchScope: "platform" },
  { path: "/mail", pageTitle: "Mail Management", breadcrumbLabel: "Mail", platformId: "portal", moduleId: "portal-mail", searchScope: "platform" },
  { path: "/offboarding", pageTitle: "Offboarding", breadcrumbLabel: "Offboarding", platformId: "portal", moduleId: "portal-offboarding", searchScope: "platform" },
  { path: "/settings", pageTitle: "Settings", breadcrumbLabel: "Settings", platformId: "portal", moduleId: "portal-settings", searchScope: "platform" },
  { path: "/design-system", pageTitle: "Design System", breadcrumbLabel: "Design System", platformId: "portal", moduleId: "portal-design-system", searchScope: "platform" },
  { path: "/talent/enterprise-architecture", pageTitle: "Enterprise Architecture", breadcrumbLabel: "Enterprise Architecture", platformId: "portal", moduleId: "portal-enterprise-architecture", searchScope: "platform" },
  { path: "/talent", pageTitle: "Talent Home", breadcrumbLabel: "Talent Home", platformId: "talent", moduleId: "talent-home", searchScope: "platform" },
  { path: "/talent/career-aspiration", pageTitle: "Career Aspiration", breadcrumbLabel: "Career Aspiration", platformId: "talent", moduleId: "talent-career-aspiration", searchScope: "platform" },
  { path: "/talent/idp", pageTitle: "Development Plan", breadcrumbLabel: "Development Plan", platformId: "talent", moduleId: "talent-idp", searchScope: "platform" },
  { path: "/talent/360-assessment", pageTitle: "360 Assessment", breadcrumbLabel: "360 Assessment", platformId: "talent", moduleId: "talent-360", searchScope: "platform" },
  { path: "/talent/competency-assessment", pageTitle: "Competency Assessment", breadcrumbLabel: "Competency Assessment", platformId: "talent", moduleId: "talent-competency", searchScope: "platform" },
  { path: "/talent/explore", pageTitle: "Job Tender Marketplace", breadcrumbLabel: "Job Tender", platformId: "talent", moduleId: "talent-job-tender", searchScope: "platform" },
  { path: "/talent/admin/job-tender", pageTitle: "Job Tender Headquarters", breadcrumbLabel: "Job Tender HQ", platformId: "talent", moduleId: "talent-job-admin", searchScope: "platform" },
  { path: "/talent/org-management", pageTitle: "Organization Management", breadcrumbLabel: "Organization Management", platformId: "talent", moduleId: "talent-org", searchScope: "platform" },
  { path: "/talent/talent-pool", pageTitle: "Talent Pool", breadcrumbLabel: "Talent Pool", platformId: "talent", moduleId: "talent-pool", searchScope: "platform" },
  { path: "/talent/succession-planning", pageTitle: "Succession Planning", breadcrumbLabel: "Succession Planning", platformId: "talent", moduleId: "talent-succession", searchScope: "platform" },
  { path: "/talent/talent-mapping", pageTitle: "Talent Classification", breadcrumbLabel: "Talent Classification", platformId: "talent", moduleId: "talent-classification", searchScope: "platform" },
  { path: "/talent/talent-review", pageTitle: "Talent Review", breadcrumbLabel: "Talent Review", platformId: "talent", moduleId: "talent-review", searchScope: "platform" },
  { path: "/performance/my-kpi", pageTitle: "My KPI", breadcrumbLabel: "My KPI", platformId: "performance", moduleId: "performance-my-kpi", searchScope: "platform" },
  { path: "/performance-v2/my-kpi", pageTitle: "My KPI", breadcrumbLabel: "My KPI", platformId: "performance-v2", moduleId: "performance-v2-my-kpi", searchScope: "platform" },
  { path: "/performance-v2/my-team-kpi/planning", pageTitle: "My Team KPI", breadcrumbLabel: "Perencanaan tim", platformId: "performance-v2", moduleId: "performance-v2-my-team", searchScope: "platform" },
  { path: "/performance-v2/my-team-kpi/monitoring", pageTitle: "My Team KPI", breadcrumbLabel: "Monitoring tim", platformId: "performance-v2", moduleId: "performance-v2-my-team", searchScope: "platform" },
  {
    path: "/performance-v2/my-team-kpi/member/:memberId",
    pageTitle: "My Team KPI",
    breadcrumbLabel: "Portofolio anggota",
    platformId: "performance-v2",
    moduleId: "performance-v2-my-team",
    hidden: true,
    searchScope: "module",
  },
  { path: "/performance-v2/kpi-library", pageTitle: "KPI Library", breadcrumbLabel: "KPI Library", platformId: "performance-v2", moduleId: "performance-v2-library", searchScope: "platform" },
  { path: "/performance-v2/kpi-tree", pageTitle: "KPI Tree", breadcrumbLabel: "KPI Tree", platformId: "performance-v2", moduleId: "performance-v2-tree", searchScope: "platform" },
  { path: "/performance-v2/kpi-headquarter", pageTitle: "KPI HQ", breadcrumbLabel: "KPI HQ", platformId: "performance-v2", moduleId: "performance-v2-hq", searchScope: "platform" },
];
